// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.29.3
// source: proto/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 订单查询请求
type QueryOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Query  string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                  // 查询内容
}

func (x *QueryOrderReq) Reset() {
	*x = QueryOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ai_ai_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderReq) ProtoMessage() {}

func (x *QueryOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderReq.ProtoReflect.Descriptor instead.
func (*QueryOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *QueryOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *QueryOrderReq) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// 订单查询响应
type QueryOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Answer string `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"` // AI回答内容
}

func (x *QueryOrderResp) Reset() {
	*x = QueryOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ai_ai_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryOrderResp) ProtoMessage() {}

func (x *QueryOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryOrderResp.ProtoReflect.Descriptor instead.
func (*QueryOrderResp) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *QueryOrderResp) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

// 自动下单请求
type AutoOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      uint32 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`      // 商品描述
}

func (x *AutoOrderReq) Reset() {
	*x = AutoOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ai_ai_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoOrderReq) ProtoMessage() {}

func (x *AutoOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoOrderReq.ProtoReflect.Descriptor instead.
func (*AutoOrderReq) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *AutoOrderReq) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AutoOrderReq) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// 自动下单响应
type AutoOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderId string `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 创建的订单ID
}

func (x *AutoOrderResp) Reset() {
	*x = AutoOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ai_ai_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AutoOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoOrderResp) ProtoMessage() {}

func (x *AutoOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoOrderResp.ProtoReflect.Descriptor instead.
func (*AutoOrderResp) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *AutoOrderResp) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

var File_proto_ai_ai_proto protoreflect.FileDescriptor

var file_proto_ai_ai_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x2f, 0x61, 0x69, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x61, 0x69, 0x22, 0x3e, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x28, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6e, 0x73,
	0x77, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6e, 0x73, 0x77, 0x65,
	0x72, 0x22, 0x49, 0x0a, 0x0c, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a, 0x0d,
	0x41, 0x75, 0x74, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x19, 0x0a,
	0x08, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x64, 0x32, 0x7b, 0x0a, 0x09, 0x41, 0x49, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x11, 0x2e, 0x61, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x61, 0x69, 0x2e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0e,
	0x41, 0x75, 0x74, 0x6f, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x10,
	0x2e, 0x61, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x11, 0x2e, 0x61, 0x69, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x64, 0x6f, 0x75, 0x79, 0x69, 0x6e, 0x2d,
	0x6d, 0x61, 0x6c, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ai_ai_proto_rawDescOnce sync.Once
	file_proto_ai_ai_proto_rawDescData = file_proto_ai_ai_proto_rawDesc
)

func file_proto_ai_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ai_ai_proto_rawDescData)
	})
	return file_proto_ai_ai_proto_rawDescData
}

var file_proto_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_ai_ai_proto_goTypes = []interface{}{
	(*QueryOrderReq)(nil),  // 0: ai.QueryOrderReq
	(*QueryOrderResp)(nil), // 1: ai.QueryOrderResp
	(*AutoOrderReq)(nil),   // 2: ai.AutoOrderReq
	(*AutoOrderResp)(nil),  // 3: ai.AutoOrderResp
}
var file_proto_ai_ai_proto_depIdxs = []int32{
	0, // 0: ai.AIService.QueryOrder:input_type -> ai.QueryOrderReq
	2, // 1: ai.AIService.AutoPlaceOrder:input_type -> ai.AutoOrderReq
	1, // 2: ai.AIService.QueryOrder:output_type -> ai.QueryOrderResp
	3, // 3: ai.AIService.AutoPlaceOrder:output_type -> ai.AutoOrderResp
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_proto_init() }
func file_proto_ai_ai_proto_init() {
	if File_proto_ai_ai_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ai_ai_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ai_ai_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ai_ai_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ai_ai_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AutoOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ai_ai_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_proto = out.File
	file_proto_ai_ai_proto_rawDesc = nil
	file_proto_ai_ai_proto_goTypes = nil
	file_proto_ai_ai_proto_depIdxs = nil
}
